//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncAwait.NewsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsServiceReference.INewsService")]
    public interface INewsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsService/GetHeadline", ReplyAction="http://tempuri.org/INewsService/GetHeadlineResponse")]
        string GetHeadline();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INewsService/GetHeadline", ReplyAction="http://tempuri.org/INewsService/GetHeadlineResponse")]
        System.IAsyncResult BeginGetHeadline(System.AsyncCallback callback, object asyncState);
        
        string EndGetHeadline(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsServiceChannel : AsyncAwait.NewsServiceReference.INewsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHeadlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHeadlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsServiceClient : System.ServiceModel.ClientBase<AsyncAwait.NewsServiceReference.INewsService>, AsyncAwait.NewsServiceReference.INewsService {
        
        private BeginOperationDelegate onBeginGetHeadlineDelegate;
        
        private EndOperationDelegate onEndGetHeadlineDelegate;
        
        private System.Threading.SendOrPostCallback onGetHeadlineCompletedDelegate;
        
        public NewsServiceClient() {
        }
        
        public NewsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetHeadlineCompletedEventArgs> GetHeadlineCompleted;
        
        public string GetHeadline() {
            return base.Channel.GetHeadline();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetHeadline(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHeadline(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetHeadline(System.IAsyncResult result) {
            return base.Channel.EndGetHeadline(result);
        }
        
        private System.IAsyncResult OnBeginGetHeadline(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetHeadline(callback, asyncState);
        }
        
        private object[] OnEndGetHeadline(System.IAsyncResult result) {
            string retVal = this.EndGetHeadline(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHeadlineCompleted(object state) {
            if ((this.GetHeadlineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHeadlineCompleted(this, new GetHeadlineCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHeadlineAsync() {
            this.GetHeadlineAsync(null);
        }
        
        public void GetHeadlineAsync(object userState) {
            if ((this.onBeginGetHeadlineDelegate == null)) {
                this.onBeginGetHeadlineDelegate = new BeginOperationDelegate(this.OnBeginGetHeadline);
            }
            if ((this.onEndGetHeadlineDelegate == null)) {
                this.onEndGetHeadlineDelegate = new EndOperationDelegate(this.OnEndGetHeadline);
            }
            if ((this.onGetHeadlineCompletedDelegate == null)) {
                this.onGetHeadlineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHeadlineCompleted);
            }
            base.InvokeAsync(this.onBeginGetHeadlineDelegate, null, this.onEndGetHeadlineDelegate, this.onGetHeadlineCompletedDelegate, userState);
        }
    }
}
